name: les_recettes_de_nathan
description: Une application de création de recettes de cuisine.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_form_builder: ^9.1.1
  provider: ^6.1.1
  url_launcher: ^6.2.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.14.0
  build_runner: ^2.4.8
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

flutter:
  assets:
    - assets/plante.png
    - assets/chrono.png
    - assets/ingredients.png
    - assets/placeholder.png
    - assets/ustensiles.png
    - assets/couverts.png
    - assets/entrees.png
    - assets/plats_chauds.png
    - assets/plats_froids.png
    - assets/plats_du_monde.png
    - assets/fast_food.png
    - assets/salades.png
    - assets/plats_fruits_de_mer.png
    - assets/viandes.png
    - assets/desserts.png
    - assets/autres.png
    - assets/soupes.png
    - assets/vegetarien.png

  fonts:
    - family: Exo2
      fonts:
        - asset: fonts/Exo2-Regular.ttf
        - asset: fonts/Exo2-Bold.ttf
        - asset: fonts/Exo2-SemiBold.ttf
    - family: LilitaOne
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf
    - family: BreeSerif
      fonts:
        - asset: fonts/BreeSerif-Regular.ttf
  uses-material-design: true